title: <p align="center"> Monika Dadhich </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="https://github.com/Monika Dadhich">GitHub</a>
  
  <br>   
  I'm working on Data Science, Big Data, Spark projects.
  <br>
  </p>

theme: jekyll-theme-minimal
